<dmb-simple-form>
    <dmb-form action="/admin/settingaddreg" id="form-project-group" name="setting" method="post" async>
        <input type="hidden" value="<?=$this->data->id;?>" name="setting[id]" />
        <dmb-header>
            <dmb-close-panel orientation="right"></dmb-close-panel>
            <? if(empty($this->data->id)): ?>
                <h3>Add reg</h3>
            <? else: ?>
                <h3>Edit</h3>
            <? endif; ?>
        </dmb-header>
        <dmb-content>
            <div class="section group">
                <div class="col col12">
                    <dmb-input
                        label="Name"
                        value="<?=$this->data->name;?>"
                        dmb-name="setting[name]"
                        validate="required"
                    ></dmb-input>
                </div>
            </div>
            <div class="section group">
                <div class="col col12">
                    <dmb-input
                        label="Value"
                        value="<?=$this->data->value;?>"
                        dmb-name="setting[value]"
                        validate="required"
                    ></dmb-input>
                </div>
            </div>
        </dmb-content>
        <dmb-footer class="section group">
            <div class="col col6">
                <dmb-button type="reset" class="button button-error" onClick="location.reload();">
                    <span class="text">Cancel</span>
                </dmb-button>
            </div>
            <div class="col col6">
                <dmb-button type="submit" class="button button-success">
                    <span class="text">Save</span>
                </dmb-button>
            </div>
        </dmb-footer>
    </dmb-form>
</dmb-simple-form>