<dmb-table>
    <table>
        <thead>
            <tr>
                <th>Aggregate Type</th>
                <th>Aggregate ID</th>
                <th>Event Type</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
            <? foreach ($this->data as $row): ?>
            <tr>
                <td><?= htmlspecialchars($row->aggregate_type, ENT_QUOTES, 'UTF-8'); ?></td>
                <td><?= $row->aggregate_id; ?></td>
                <td><?= htmlspecialchars($row->event_type, ENT_QUOTES, 'UTF-8'); ?></td>
                <td><?= date('Y-m-d H:i:s', $row->created_at); ?></td>
            </tr>
            <? endforeach; ?>
        </tbody>
    </table>
</dmb-table>

<dmb-pagination>
    Página: <?= $this->data->WillPaginate($this->fullUrl()); ?>
    de <?= $this->data->PaginateTotalPages; ?>
</dmb-pagination>
