<dmb-table>
    <table>
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Tipo</th>
                <th>Estado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            <? foreach ($this->data as $row): ?>
            <tr>
                <td><?= $row->name; ?></td>
                <td><?= $row->type; ?></td>
                <td><?= $this->statuses[$row->status]; ?></td>
                <td>
                    <dmb-more-options>
                        <dmb-more-option
                            behavior="launch-url"
                            url="/admin/project_config_files?project_id=<?= $row->id; ?>">
                            Ver archivos
                        </dmb-more-option>
                        <dmb-more-option
                            behavior="open-panel"
                            url="/admin/projects/edit/<?= $row->id; ?>"
                            panel="#panel-form-add-edit-reg">
                            Editar
                        </dmb-more-option>
                        <dmb-more-option
                            behavior="ajax"
                            url="/admin/projects/<?= $row->id; ?>">
                            Eliminar
                        </dmb-more-option>
                    </dmb-more-options>
                </td>
            </tr>
            <? endforeach; ?>
        </tbody>
    </table>
</dmb-table>

<dmb-dock id="admin-dock-options">
    <div class="item" data-title="Agregar">
        <dmb-button-action
            action="new"
            panel="#panel-form-add-edit-reg"
            url="/admin/projects/add"
            behavior="open-panel">
        </dmb-button-action>
    </div>
</dmb-dock>

<dmb-pagination>
    Página: <?= $this->data->WillPaginate($this->fullUrl()); ?>
    de <?= $this->data->PaginateTotalPages; ?>
</dmb-pagination>
