<dmb-simple-form>
    <dmb-form action="/project/addreg" id="form-project" name="project" method="post" async>
        <input type="hidden" value="<?=$this->data->id;?>" name="project[id]" />
        <dmb-header>
            <dmb-close-panel orientation="right"></dmb-close-panel>
            <? if(empty($this->data->id)): ?>
                <h3>Add reg</h3>
            <? else: ?>
                <h3>Edit</h3>
            <? endif; ?>
        </dmb-header>
        <dmb-content>
            <div class="section group">
                <div class="col col12">
                    <dmb-input
                        label="Name"
                        value="<?=$this->data->name;?>"
                        dmb-name="project[name]"
                        validate="required"
                    ></dmb-input>
                </div>
            </div>
            <div class="section group">
                <div class="col col12">
                    <dmb-input
                        label="path"
                        value="<?=$this->data->path;?>"
                        dmb-name="project[path]"
                        validate="required"
                    ></dmb-input>
                </div>
            </div>
            <div class="section group">
                <div class="col col12">
                    <dmb-select
                        label="Build after"
                        dmb-value="<?=$this->data->run_after;?>"
                        dmb-name="project[run_after]"
                    >
                        <option value="0"></option>
                        <? foreach($this->projects as $project): ?>
                        <option value="<?=$project->id?>"><?=$project->name;?></option>
                        <? endforeach; ?>
                    </dmb-select>
                </div>
            </div>
            <div class="section group">
                <div class="col col12">
                    <dmb-select
                        label="Group"
                        dmb-value="<?=$this->data->run_after;?>"
                        dmb-name="project[project_group_id]"
                    >
                        <option value="0"></option>
                        <? foreach($this->groups as $group): ?>
                        <option value="<?=$group->id?>"><?=$group->name;?></option>
                        <? endforeach; ?>
                    </dmb-select>
                </div>
            </div>
            <div class="section group">
                <div class="col col12">
                    <dmb-select
                        label="Clone commands from another project"
                        dmb-name="project[clone_from]"
                    >
                        <option value="0"></option>
                        <? foreach($this->projects as $project): ?>
                        <option value="<?=$project->id?>"><?=$project->name;?></option>
                        <? endforeach; ?>
                    </dmb-select>
                </div>
            </div>
        </dmb-content>
        <dmb-footer class="section group">
            <div class="col col6">
                <dmb-button type="reset" class="button button-error" onClick="location.reload();"><span class="text">Cancel</span></dmb-button>
            </div>
            <div class="col col6">
                <dmb-button type="submit" class="button button-success"><span class="text">Save</span></dmb-button>
            </div>
        </dmb-footer>
    </dmb-form>
</dmb-simple-form>