    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Uroboros CI/CD</title>
    <meta name="viewport" content="initial-scale=1, width=device-width">
    <meta name="description" content="Continuos Integration, Continuos Delivery">
    <meta name="keywords" content="continous,integration,delivery">

    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <style type="text/css">
    :root {
        --primary: #007bff;
        --primary-contrast: #FFFFFF;
        --primary-hover: #007bff99;
        --secondary: #6c757d;
        --secondary-contrast: #FFFFFF;
        --secondary-hover: #6c757d99;
        --default: #000000;
        --default-contrast: #FFFFFF;
        --default-hover: #99999999;
        --success: #28a745;
        --success-contrast: #FFFFFF;
        --success-hover: #28a74599;
        --information: #17a2b8;
        --information-contrast: #FFFFFF;
        --information-hover: #17a2b899;
        --warning: #ffc107;
        --warning-contrast: #FFFFFF;
        --warning-hover: #ffc10799;
        --error: #dc3545;
        --error-contrast: #FFFFFF;
        --error-hover: #dc354599;
        --hover-opacity: 0.5;
    }

    @font-face {
        font-family: 'icomoon';
        font-display: fallback;
        font-style: normal;
        font-weight: normal;
        src:url('/fonts/icomoon/icomoon.woff');
        src:url('/fonts/icomoon/icomoon.eot?#iefix') format('embedded-opentype'),
            url('/fonts/icomoon/icomoon.woff') format('woff'),
            url('/fonts/icomoon/icomoon.ttf') format('truetype'),
            url('/fonts/icomoon/icomoon.svg') format('svg');
    }

    @font-face {
        font-family: 'OpenSansRegular', sans-serif;
        font-display: swap;
        font-style: normal;
        font-weight: normal;
        src:url('/fonts/openSans/Regular/OpenSans-Regular.ttf');
        src:url('/fonts/openSans/Regular/OpenSans-Regular.otf') format('opentype'),
            url('/fonts/openSans/Regular/OpenSans-Regular.woff') format('woff'),
            url('/fonts/openSans/Regular/OpenSans-Regular.ttf') format('truetype'),
            url('/fonts/openSans/Regular/OpenSans-Regular.svg') format('svg');
    }

    <?
    readfile(INST_PATH.'app/webroot/libs/dmb-styles.css');

    readfile(INST_PATH.'app/webroot/css/styles.css');
    ?>
    </style>
    <script type="text/javascript">
        window.innerWidth = window.outerWidth;
    </script>