    <title>Uroboros</title>
    <meta charset="utf-8"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta http-equiv="Cache-Control" content="public" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Uroboros Operational Event Mesh (UOEM) is a web-based platform for managing and monitoring operational events in real-time. It provides a centralized interface for event collection, correlation, and visualization, enabling organizations to gain insights into their operational processes and make informed decisions. UOEM supports various event sources, including logs, metrics, and alerts, and offers features such as event filtering, aggregation, and notification. With UOEM, organizations can improve their operational efficiency, reduce downtime, and enhance overall system reliability.">
    <meta name="keywords" content="Uroboros, UOEM, Operational Event Mesh, event management, real-time monitoring, event collection, event correlation, event visualization, operational processes, event filtering, event aggregation, event notification, system reliability">
    <meta name="theme-color" content="#16253F">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/logo.svg">
    <meta name="msapplication-starturl" content="/">
    <meta name="base-uri" content="self" />


    <link rel="apple-touch-icon" sizes="57x57" href="/images/logo.svg">
    <link rel="apple-touch-icon" sizes="60x60" href="/images/logo.svg">
    <link rel="apple-touch-icon" sizes="72x72" href="/images/logo.svg">
    <link rel="apple-touch-icon" sizes="76x76" href="/images/logo.svg">
    <link rel="apple-touch-icon" sizes="114x114" href="/images/logo.svg">
    <link rel="apple-touch-icon" sizes="120x120" href="/images/logo.svg">
    <link rel="apple-touch-icon" sizes="144x144" href="/images/logo.svg">
    <link rel="apple-touch-icon" sizes="152x152" href="/images/logo.svg">
    <link rel="apple-touch-icon" sizes="180x180" href="/images/logo.svg">
    <link rel="icon" type="image/svg+xml" sizes="192x192"  href="/images/logo.svg">
    <link rel="icon" type="image/svg+xml" sizes="32x32" href="/images/logo.svg">
    <link rel="icon" type="image/svg+xml" sizes="96x96" href="/images/logo.svg">
    <link rel="icon" type="image/svg+xml" sizes="16x16" href="/images/logo.svg">
    <link rel="manifest" href="/<?=$this->_getController_();?>-manifest.json">
    <link rel="preconnect" href="/" />
    <link rel="canonical" href="https://uroboros.rantes.local/admin/" />

    <link rel="preload" as="style" type="text/css" href="/ui-components/libs/main.css">
    <link rel="preload" as="style" type="text/css" href="/css/styles.css">
    
    <link rel="preload" as="script" href="/ui-components/actions/app.js" crossOrigin="same">

    <link rel="stylesheet" type="text/css" href="/ui-components/libs/main.css">
    <link rel="stylesheet" type="text/css" href="/css/styles.css">

    <script src="/ui-components/actions/app.js" type="module" nonce="<?=$this->nonce;?>"></script>
