<template id="Dmb-booking-calendar-template"><p>This is the dmb-booking-calendar component</p></template>
<template id="Dmb-clock-template"></template>
<template id="DmbClosePanel-template"><span icon="chevron_left"></span></template>
<template id="Dmb-config-pending-template"></template>
<template id="DmbDialog-template"><dmb-view class="wrapper" transclude></dmb-view></template>
<template id="DmbIdReader-template"><dmb-dialog no-auto-open no-close>    <div class="dmb-id-reader">        <div class="section group">            <div class="col col12">                <h3 class="title">                    Active el lector o continue manualmente...
                </h3>            </div>        </div>        <div class="section group">            <div class="col col1"></div>            <div class="col col10">                <dmb-button
                    id="pedestrian-in-manually"
                    class="primary button">                    Manualmente
                </dmb-button>            </div>            <div class="col col1"></div>        </div>        <dmb-form method="post" action="#" class="reader-form"
            autocomplete="off" name="reader" async>            <input class="reader-field" tabindex="1" autocomplete="off"
                type="text" name="number" autofocus>            <input class="reader-field" tabindex="2" autocomplete="off"
                type="text" name="lastname">            <input class="reader-field" tabindex="3" autocomplete="off"
                type="text" name="secondlastname">            <input class="reader-field" tabindex="4" autocomplete="off"
                type="text" name="firstname" value="javier">            <input class="reader-field" tabindex="5" autocomplete="off"
                type="text" name="secondname">            <input class="reader-field" tabindex="6" autocomplete="off"
                type="text" name="gender">            <input class="reader-field" tabindex="7" autocomplete="off"
                type="text" name="birthdate">            <input class="reader-field" tabindex="8" autocomplete="off"
                type="text" name="blood">            <input class="reader-field" tabindex="9" autocomplete="off"
                type="text" name="field1">        </dmb-form>    </div></dmb-dialog></template>
<template id="Dmb-image-uploader-template"><dmb-input type="file" dmb-name="imgfile" accept="image/*"></dmb-input><div class="preview">    <img src="#" alt=""></div></template>
<template id="DmbMenuButton-template"><span icon="menu"></span><span class="legend" transclude></span></template>
<template id="Dmb-push-subscribe-template"><p>This is the dmb-push-subscribe component</p></template>
<template id="Dmb-reception-type-select-template"><p>This is the dmb-reception-type-select component</p></template>
<template id="Dmb-status-badge-template"><span transclude></span></template>
<template id="Dmb-tree-view-template"><ul class="trunk" transclude></ul></template>
<template id="Dmb-video-uploader-template"><dmb-input type="file" dmb-name="videofile" accept="video/*"></dmb-input><div class="preview">    <video controls></video></div>'</template>
<template id="Dmb-wysiwyg-template"></template>
