<!DOCTYPE html>
<html lang="en">
<head>
    <? require_once(INST_PATH.'app/views/_header-contents.phtml'); ?>
</head>
<body>
    <noscript>
        <h1>Your browser does not support JS</h1>
    </noscript>
    <dmb-view id="page">
	    <dmb-header class="section group">
            <div class="col col2"></div>
            <div class="col col8">Uroboros CI/CD</div>
            <div class="col col2"><a href="/index/logout">Cerrar sesi&oacute;n</a></div>
        </dmb-header>
        <dmb-content>
        <?=$this->yield;?>
        </dmb-content>
    </dmb-view>
    <? require_once(INST_PATH.'app/views/_footer-contents.phtml'); ?>
</body>
</html>